[tool.ruff]
lint.ignore = ["C901", "E501", "E741", "W605"]
lint.select = ["C", "E", "F", "I", "W"]
line-length = 119
extend-include = ["*.ipynb"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]