name: CI

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Typos check
        uses: crate-ci/typos@master
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print all TODO markings
        run: grep -e TODO * -r
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ruff
        run: pip install ruff
      - name: Check code quality
        run: make quality