name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  pytest:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -e /home/runner/work/mole/
      - run: python -m pytest -s -v /home/runner/work/mole/tests